version: '3'
services:
  angular-api:
    container_name: angular-api
    image: agustinsilvanoatt/dotnet-refresh:dev
    environment:
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pass123 #Dev-cert password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx # Dev cert full path inside container.
        - PROJECT=Angular4KickOffBE
    volumes:
      - ./:/code/app #App code
      - ./conf.d/https/:/https/ #This volume store the dev-cert, should be mapped from the host machine. Ref : https://tomssl.com/how-to-run-asp-net-core-3-1-over-https-in-docker-using-linux-containers/
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - dotnet-dev
networks:
  dotnet-dev: