version: '3'
services:
  angular-api:
    container_name: angular-api
    image: angular-api:dev
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+;
        - ASPNETCORE_HTTPS_PORT=44311
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pass123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    build:
      context: ./Angular4KickOffBE
      dockerfile: Dockerfile
    volumes:
      - ./Angular4KickOffBE:/code/app
      - ./conf.d/https/:/https/
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - dotnet-dev
networks:
  dotnet-dev: